// Mock data for splitUP expense tracking app

export const mockUser = {
  id: 'user-1',
  name: 'Akshaya',
  email: 'akshaya@edu.in',
  avatar: null,
};

export const mockGroups = {
  "apartment-402": {
    id: "apartment-402",
    name: "Apartment 402",
    type: "home",
    createdAt: "Oct 2023",
    inviteCode: "X8J2-9K",
    memberCount: 6,
    totalSpent: 12450,
    remaining: 3550,
    currency: "INR",
    members: [
      {
        id: "1",
        name: "Akshaya",
        email: "akshaya@example.com",
        avatar_url: null,
        role: "admin",
        joinedDate: "Oct 12, 2023",
        status: "active",
        isYou: true,
      },
      {
        id: "2",
        name: "Sarah Chen",
        email: "sarah.c@example.com",
        avatar_url: null,
        role: "member",
        joinedDate: "Oct 14, 2023",
        status: "offline",
      },
      {
        id: "3",
        name: "Mike Ross",
        email: "mike.ross@example.com",
        avatar_url: null,
        role: "member",
        joinedDate: "Nov 02, 2023",
        status: "active",
      },
      {
        id: "4",
        name: "Elena Gomez",
        email: "elena.g@example.com",
        avatar_url: null,
        role: "member",
        joinedDate: "Dec 05, 2023",
        status: "offline",
      },
      {
        id: "5",
        name: "Jenny Wilson",
        email: "jenny.w@example.com",
        avatar_url: null,
        role: "member",
        joinedDate: "Dec 10, 2023",
        status: "active",
      },
      {
        id: "6",
        name: "David Kim",
        email: "david.k@example.com",
        avatar_url: null,
        role: "member",
        joinedDate: "Jan 05, 2024",
        status: "offline",
      },
    ],
    expenses: [
      {
        id: "1",
        title: "Dinner at SpiceHub",
        category: "Food",
        amount: 1200,
        paidBy: { id: "1", name: "You" },
        splitType: "Split equally",
        date: "Mar 12",
        color: "#2AB3A4",
      },
      {
        id: "2",
        title: "March Rent",
        category: "Rent",
        amount: 18000,
        paidBy: { id: "2", name: "Sarah" },
        splitType: "Split equally",
        date: "Mar 01",
        color: "#3B82F6",
      },
      {
        id: "3",
        title: "Weekend Trip Cab",
        category: "Travel",
        amount: 3450,
        paidBy: { id: "3", name: "Mike" },
        splitType: "Custom split",
        date: "Mar 03",
        color: "#F59E0B",
      },
      {
        id: "4",
        title: "Grocery Run",
        category: "Groceries",
        amount: 850,
        paidBy: { id: "1", name: "You" },
        splitType: "Split by shares",
        date: "Feb 28",
        color: "#8B5CF6",
      },
    ],
    balances: {
      yourBalance: -800,
      youOwe: 1250,
      youAreOwed: 450,
      peopleYouOwe: [
        {
          id: "3",
          name: "Mike Ross",
          avatar_url: null,
          amount: 1250,
          reason: "WiFi & Electricity Bill",
        },
      ],
      peopleWhoOweYou: [
        {
          id: "2",
          name: "Sarah Miller",
          avatar_url: null,
          amount: 450,
          reason: "Pizza Night",
        },
      ],
      otherBalances: [{ from: "Jenny", to: "Mike", amount: 200 }],
    },
    budgets: {
      total: 44000,
      spent: 33450,
      remaining: 10550,
      percentageUsed: 76,
      categories: [
        {
          id: "1",
          name: "Groceries",
          icon: "shopping-cart",
          spent: 12400,
          limit: 20000,
          status: "safe",
        },
        {
          id: "2",
          name: "Rent & Utilities",
          icon: "home",
          spent: 15000,
          limit: 15000,
          status: "limit-reached",
        },
        {
          id: "3",
          name: "Entertainment",
          icon: "party",
          spent: 4250,
          limit: 5000,
          status: "nearing-limit",
        },
        {
          id: "4",
          name: "Electricity",
          icon: "zap",
          spent: 1800,
          limit: 4000,
          status: "on-track",
        },
      ],
    },
  },
  "goa-trip-2024": {
    id: "goa-trip-2024",
    name: "Goa Trip 2024",
    type: "trip",
    createdAt: "Jan 2024",
    inviteCode: "GT24-7X",
    memberCount: 6,
    totalSpent: 42500,
    remaining: 7500,
    currency: "INR",
    members: [
      {
        id: "1",
        name: "Akshaya",
        email: "akshaya@example.com",
        avatar_url: null,
        role: "admin",
        joinedDate: "Jan 05, 2024",
        status: "active",
        isYou: true,
      },
      {
        id: "2",
        name: "Ravi Kumar",
        email: "ravi.k@example.com",
        avatar_url: null,
        role: "member",
        joinedDate: "Jan 06, 2024",
        status: "active",
      },
      {
        id: "3",
        name: "Priya Sharma",
        email: "priya.s@example.com",
        avatar_url: null,
        role: "member",
        joinedDate: "Jan 06, 2024",
        status: "offline",
      },
    ],
    expenses: [
      {
        id: "1",
        title: "Hotel Booking",
        category: "Stay",
        amount: 24000,
        paidBy: { id: "1", name: "You" },
        splitType: "Split equally",
        date: "Jan 15",
        color: "#3B82F6",
      },
      {
        id: "2",
        title: "Flight Tickets",
        category: "Travel",
        amount: 18500,
        paidBy: { id: "2", name: "Ravi" },
        splitType: "Split equally",
        date: "Jan 10",
        color: "#F59E0B",
      },
    ],
    balances: {
      yourBalance: 450,
      youOwe: 0,
      youAreOwed: 450,
      peopleYouOwe: [],
      peopleWhoOweYou: [
        {
          id: "3",
          name: "Priya Sharma",
          avatar_url: null,
          amount: 450,
          reason: "Cab to airport",
        },
      ],
      otherBalances: [],
    },
    budgets: {
      total: 50000,
      spent: 42500,
      remaining: 7500,
      percentageUsed: 85,
      categories: [
        {
          id: "1",
          name: "Stay",
          icon: "home",
          spent: 24000,
          limit: 25000,
          status: "nearing-limit",
        },
        {
          id: "2",
          name: "Travel",
          icon: "plane",
          spent: 18500,
          limit: 20000,
          status: "safe",
        },
      ],
    },
  },
  "office-lunch": {
    id: "office-lunch",
    name: "Office Lunch",
    type: "other",
    createdAt: "Feb 2024",
    inviteCode: "OL24-3M",
    memberCount: 3,
    totalSpent: 5600,
    remaining: 400,
    currency: "INR",
    members: [
      {
        id: "1",
        name: "Akshaya",
        email: "akshaya@example.com",
        avatar_url: null,
        role: "admin",
        joinedDate: "Feb 01, 2024",
        status: "active",
        isYou: true,
      },
      {
        id: "2",
        name: "John Doe",
        email: "john.d@example.com",
        avatar_url: null,
        role: "member",
        joinedDate: "Feb 02, 2024",
        status: "active",
      },
      {
        id: "3",
        name: "Lisa Park",
        email: "lisa.p@example.com",
        avatar_url: null,
        role: "member",
        joinedDate: "Feb 03, 2024",
        status: "offline",
      },
    ],
    expenses: [
      {
        id: "1",
        title: "Team Lunch Friday",
        category: "Food",
        amount: 2400,
        paidBy: { id: "1", name: "You" },
        splitType: "Split equally",
        date: "Mar 08",
        color: "#2AB3A4",
      },
      {
        id: "2",
        title: "Coffee Run",
        category: "Food",
        amount: 450,
        paidBy: { id: "2", name: "John" },
        splitType: "Split equally",
        date: "Mar 10",
        color: "#2AB3A4",
      },
    ],
    balances: {
      yourBalance: 0,
      youOwe: 0,
      youAreOwed: 0,
      peopleYouOwe: [],
      peopleWhoOweYou: [],
      otherBalances: [],
    },
    budgets: {
      total: 6000,
      spent: 5600,
      remaining: 400,
      percentageUsed: 93,
      categories: [
        {
          id: "1",
          name: "Food & Drinks",
          icon: "utensils",
          spent: 5600,
          limit: 6000,
          status: "nearing-limit",
        },
      ],
    },
  },
};

// Activity feed data
export const mockActivity = [
  {
    id: "1",
    type: "expense",
    message: "You added \"Dinner at SpiceHub\" in Apartment 402",
    amount: 1200,
    timestamp: "2 hours ago",
    groupId: "apartment-402",
  },
  {
    id: "2",
    type: "payment",
    message: "Sarah settled up with you",
    amount: 450,
    timestamp: "Yesterday",
    groupId: "apartment-402",
  },
  {
    id: "3",
    type: "expense",
    message: "Mike added \"Weekend Trip Cab\" in Apartment 402",
    amount: 3450,
    timestamp: "2 days ago",
    groupId: "apartment-402",
  },
  {
    id: "4",
    type: "joined",
    message: "You joined Goa Trip 2024",
    timestamp: "1 week ago",
    groupId: "goa-trip-2024",
  },
  {
    id: "5",
    type: "expense",
    message: "Ravi added \"Flight Tickets\" in Goa Trip 2024",
    amount: 18500,
    timestamp: "1 week ago",
    groupId: "goa-trip-2024",
  },
];

// Stats for dashboard
export const mockStats = {
  totalGroups: 3,
  spentThisMonth: 12450,
  spentChange: 12,
  youOwe: 1200,
  owedTo: "2 friends",
  youAreOwed: 450,
  owedFrom: "1 friend",
};

// Category colors and icons mapping
export const categoryConfig = {
  Food: { color: "#2AB3A4", bgColor: "bg-primary-muted", textColor: "text-primary" },
  Rent: { color: "#3B82F6", bgColor: "bg-blue-50", textColor: "text-blue-600" },
  Travel: { color: "#F59E0B", bgColor: "bg-amber-50", textColor: "text-amber-600" },
  Groceries: { color: "#8B5CF6", bgColor: "bg-purple-50", textColor: "text-purple-600" },
  Utilities: { color: "#10B981", bgColor: "bg-emerald-50", textColor: "text-emerald-600" },
  Stay: { color: "#3B82F6", bgColor: "bg-blue-50", textColor: "text-blue-600" },
  Entertainment: { color: "#EC4899", bgColor: "bg-pink-50", textColor: "text-pink-600" },
  Other: { color: "#6B7280", bgColor: "bg-gray-50", textColor: "text-gray-600" },
};
